[package]
name = "stress"
version = "0.1.0"
authors = ["The TiKV Authors"]
edition = "2018"

[dependencies]
clap = "2.32"
const_format = "0.2.13"
hdrhistogram = "6.0"
raft = { git = "https://github.com/tikv/raft-rs", branch = "master", default-features = false, features = ["protobuf-codec"] }
raft-engine = { path = ".." }
rand = "0.7"
rand_distr = "0.3"
statistical = "1.0.0"
